export const AdminTypes = {
    CREATE_NEW_PRODUCT_REQUEST: 'CREATE_NEW_PRODUCT_REQUEST',
    CREATE_NEW_PRODUCT_SUCCESS: 'CREATE_NEW_PRODUCT_SUCCESS',
    CREATE_NEW_PRODUCT_FAILURE: 'CREATE_NEW_PRODUCT_FAILURE',

    GET_ORDERS_REQUEST: 'GET_ORDERS_REQUEST', 
    GET_ORDERS_SUCCESS: 'GET_ORDERS_SUCCESS', 
    GET_ORDERS_FAILURE: 'GET_ORDERS_FAILURE',
}