export const UserTypes = {
    GET_USER_ORDERS_REQUEST: 'GET_USER_ORDERS_REQUEST', 
    GET_USER_ORDERS_SUCCESS: 'GET_USER_ORDERS_SUCCESS', 
    GET_USER_ORDERS_FAILURE: 'GET_USER_ORDERS_FAILURE',

    CREATE_ORDER_REQUEST: 'CREATE_ORDER_REQUEST', 
    CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS', 
    CREATE_ORDER_FAILURE: 'CREATE_ORDER_FAILURE',
} 