export const ProductTypes = {
    GET_PRODUCT_REQUEST: 'GET_PRODUCT_REQUEST',
    GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
    GET_PRODUCT_FAILURE: 'GET_PRODUCT_FAILURE',

    GET_PRODUCTS_REQUEST: 'GET_PRODUCTS_REQUEST',
    GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_FAILURE: 'GET_PRODUCTS_FAILURE',

    GET_SIZES_REQUEST: 'GET_SIZES_REQUEST',
    GET_SIZES_SUCCESS: 'GET_SIZES_SUCCESS',
    GET_SIZES_FAILURE: 'GET_SIZES_FAILURE',

    GET_SEASONS_REQUEST: 'GET_SEASONS_REQUEST',
    GET_SEASONS_SUCCESS: 'GET_SEASONS_SUCCESS',
    GET_SEASONS_FAILURE: 'GET_SEASONS_FAILURE',
    
    GET_BRANDS_REQUEST: 'GET_BRANDS_REQUEST',
    GET_BRANDS_SUCCESS: 'GET_BRANDS_SUCCESS',
    GET_BRANDS_FAILURE: 'GET_BRANDS_FAILURE',

    ADD_TO_CART: 'ADD_TO_CART',

    EDIT_PRODUCT_REQUEST: 'EDIT_PRODUCT_REQUEST',
    EDIT_PRODUCT_SUCCESS: 'EDIT_PRODUCT_SUCCESS',
    EDIT_PRODUCT_FAILURE: 'EDIT_PRODUCT_FAILURE',

    DELETE_PRODUCT_REQUEST: 'DELETE_PRODUCT_REQUEST',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILURE: 'DELETE_PRODUCT_FAILURE',
} 